In [5]:
import numpy as np 

LES CONSTRUCTEURS

In [6]:
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
c = np.ones((4,5))
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
#renvoie une liste de nombres entiers de 1 a 59
l = np.arange(1,60)

THE MOST FAMOUS ATTRIBUTE

In [10]:
c.shape

(4, 5)

In [11]:
c.size

20

#_________________________________________________________________________________________________________________

In [12]:
d = np.random.randn(10,10)
d

array([[ 0.08407446, -0.48902131,  0.9344611 , -0.72096288, -0.02147807,
        -0.17600459, -0.01629189,  0.55384051,  2.13722012,  1.21165608],
       [-0.1732423 ,  0.09057699,  0.57035374, -0.43997405, -0.43451853,
         3.25748597, -0.84736029, -0.25767543, -3.03631939,  1.82636591],
       [-0.55809323,  0.02627829,  0.78792753,  0.98673109,  0.1246545 ,
         0.78053821, -0.44018464,  0.10953618,  1.08508448,  0.81290749],
       [-0.59703625,  1.30120892, -0.56229422, -0.42878547, -1.01429245,
        -0.08772336,  0.6447964 , -0.65726666, -0.53257401, -0.88678009],
       [ 0.29036256,  0.07119762,  0.33319677,  1.24395987,  0.13711513,
        -0.3872385 , -1.16074362,  1.01601688,  0.84037968,  0.71126137],
       [-0.46839936,  1.61334002, -1.21033468,  0.26723589,  0.16850808,
         0.77906693,  0.90222161, -0.92233419, -1.48107721,  0.57197206],
       [-0.09551624, -1.18959171,  0.14396455,  1.7919142 ,  1.85886233,
        -0.44798788, -0.56715845,  1.1104448 

In [13]:
np.random.seed(1)
d = np.random.randn(10,10)
d 

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
        -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
        -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521],
       [-1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595,
        -0.68372786, -0.12289023, -0.93576943, -0.26788808,  0.53035547],
       [-0.69166075, -0.39675353, -0.6871727 , -0.84520564, -0.67124613,
        -0.0126646 , -1.11731035,  0.2344157 ,  1.65980218,  0.74204416],
       [-0.19183555, -0.88762896, -0.74715829,  1.6924546 ,  0.05080775,
        -0.63699565,  0.19091548,  2.10025514,  0.12015895,  0.61720311],
       [ 0.30017032, -0.35224985, -1.1425182 , -0.34934272, -0.20889423,
         0.58662319,  0.83898341,  0.93110208,  0.28558733,  0.88514116],
       [-0.75439794,  1.25286816,  0.51292982, -0.29809284,  0.48851815,
        -0.07557171,  1.13162939,  1.51981682

CONSTRUCTEUR TABLEAU A UNE DIMENTION 

In [14]:
e = np.linspace(0, 10, 30)
e

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [15]:
f = np.arange(0,10,0.5)
f

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

FIXER LE NOMBRE DE BIT AUE PRENNENT NOS VALEUR DANS LES TABLEAU


In [16]:
e = np.linspace(0, 10, 30, dtype=np.float16)
e

array([ 0.    ,  0.3447,  0.6895,  1.034 ,  1.379 ,  1.725 ,  2.068 ,
        2.414 ,  2.758 ,  3.104 ,  3.45  ,  3.793 ,  4.137 ,  4.484 ,
        4.83  ,  5.17  ,  5.516 ,  5.863 ,  6.207 ,  6.55  ,  6.9   ,
        7.242 ,  7.586 ,  7.93  ,  8.27  ,  8.62  ,  8.97  ,  9.31  ,
        9.66  , 10.    ], dtype=float16)

In [17]:
#on peut le faire avec n'importe quel constructeur de tableau

METHODES MANIPULANT LES TABLEAU 

In [18]:
a = np.zeros((5,6))
b = np.ones((5,6))

In [19]:
#pile horizontal
np.hstack((a,b))

array([[0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.]])

In [20]:
#pile vertical
np.vstack((a,b))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
# axis0 = y axis / axis1 = x axis / axis2 = z axis
np.concatenate((a,b), axis=1)

array([[0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.]])

In [22]:
a.shape

(5, 6)

In [23]:
#edimentionner notre tableau toute en gardant le meme size
a = a.reshape((10, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
#TRANSFORNER UN ARRAY EN UNE LISTE (1d)
a.ravel()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
#transposer le array 
a.T

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
lol = np.linspace(0, 10)
lol

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
#construit two matrix with 
(x,y) = np.meshgrid([1,2,3], [1,2,3])

In [36]:
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [37]:
y

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])