In [1]:
import numpy as np

In [2]:
#numpy table construct
a = np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [3]:
#display type
a.dtype

dtype('int32')

In [4]:
type(a)

numpy.ndarray

In [5]:
#NO rows and NO columns
a.shape

(2, 5)

In [6]:
#NO rows * NO columns = size
a.size

10

In [29]:
a = np.array([[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]] )

In [30]:
a[:, 2] = 10
a

array([[ 1,  2, 10,  4,  5,  6,  7,  8,  9],
       [ 1,  2, 10,  4,  5,  6,  7,  8,  9]])

In [9]:
np.savetxt('test.csv', a, fmt = '%.1f', delimiter = ',')

In [10]:
import os
os.getcwd()

'C:\\Users\\dina ouahbi'

In [11]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
ls = np.linspace(1, 4, 100)

# CONDITIONAL STRUCTUR


In [13]:
a = int(input('enter marks : '))
if a>= 85:
    print("A Grade")
elif a < 85 and a>=80:
    print("A-Grade")
elif a < 80 and a>=75:
    print("B-Grade")
elif a < 75 and a>=70:
    print("B-Grade")
else:
    print("Bellow average")

enter marks : 64
Bellow average


In [14]:
a=3
if a>10:
    print(">10")
elif not a>10:
    print("<10")

<10


# nested if


In [19]:
x = int(input("Enter your integer number please : "))
if x>10:
    print("above 10 / inside the top if")
    if x>20:
        print("and above 20 / inside the nested if")
        if x>30:
            print("and above 30 / inside the nested if")
    else:
        print("but not above 20, noor 30")         
print("outside the ifs")

Enter your integer number please : 24
above 10 / inside the top if
and above 20 / inside the nested if
outside the ifs


In [20]:
"""
multiline comment  

"""

'\nmultiline comment  \n\n'

# user enter float, i will return the integer portion before the flot number

In [24]:
x = float(input("float number ? "))
y = round(x)
if x>0:
    if x>y:
        integPortion = y - 1
    else:
        integPortion = y
else:
    if y<x:
        integPortion = y+1
    else:
        integPortion = y
print(integPortion)


float number ? -87.3
-87


# LOOPS


In [5]:
x = int(input("enter x : "))
i = 1
while i<x:
    print(i**2)
    print("this is iterateion number : {}".format(i))
    i+=1
print("loop done")

enter x : 3
1
this is iterateion number : 1
4
this is iterateion number : 2
loop done


In [6]:
#print the pair value 
x = int(input("enter x : "))
i = 1
while i<x:
    if i%2==0:
        print(i)
    else:
        pass
    i+=1
print("loop done")

enter x : 10
2
4
6
8
loop done


In [14]:
#while loop with conditions
i = 1
while True:
    if i%5 == 0:
        print("break")
        break
    else:
        print(i,"inside else")
        i+=1
        continue
    print("inside loop")
print("done")

1 inside else
2 inside else
3 inside else
4 inside else
break
done


In [20]:
#for loop 
l1 =[]
l2 = []
for i in range(0,10,2):
    l1.append(i)
    l2.append(i**2)
print(l1)
print(l2)

[0, 2, 4, 6, 8]
[0, 4, 16, 36, 64]


In [29]:
#else in for loop 
s = {"apple", 2,"dina"}
for x in s:
    print("  ",x)
    print("|-------|")
else:
    print('loop done')

   dina
|-------|
   2
|-------|
   apple
|-------|
loop done


In [33]:
#loop for with dictionary
dic = {"Name":"dina", "Age":25, "Sex":"F"}
for x in dic:
    print(x,"================>",dic[x])

Name ================> dina
Age ================> 25
Sex ================> F


In [ ]:
L = [1,2,4,-5,7,9,3,2]
Lmin = []
c = 0
m = L[0]
while c<len(L):
    for i in L:
        if i<m:
            m=i
            Lmin.append(m)
            c+=1
print(Lmin)

# FUNCTIONS

In [2]:
def printSuccess():
    """this function is doing nothing except printing a message.
    that msg is "hello"
    """
    print("Hello")

In [4]:
#gives a docSTRING about this function
printSuccess?

In [10]:
#tel us hat the function is doing
help(printSuccess)

Help on function printSuccess in module __main__:

printSuccess()
    this function is doing nothing except printing a message.
    that msg is "hello"



In [21]:
#function with argument
def printMsg(msg):
    """this function print a specfic msg"""
    if isinstance(msg,str):
        print(msg)
    else:
        print("your input arg is not a string, : {}".format(msg))

In [22]:
printMsg("hello, i\'m Dina and welcom to my Basic Python Tutorial")

hello, i'm Dina and welcom to my Basic Python Tutorial


In [23]:
printMsg(123456)

your input arg is not a string, : 123456


In [24]:
help(printMsg)

Help on function printMsg in module __main__:

printMsg(msg)
    this function print a specfic msg



In [26]:
#with more than one arg 
def myPow(x,y):
    """this function calculate the power just like builtin pow function """
    return x**y

In [28]:
myPow(3,4)

81

In [29]:
#this function takes tree arguments
def chekVal(a,b,c):
    if isinstance(a, (int,float)) and isinstance(b, (int,float)) and isinstance(c, (int,float)):
        print((a+b+c)**2)
    else:
        print("Error")
    

In [33]:
chekVal("ff",4,5)
chekVal(5,4,5)

Error
196


In [1]:
print("hello")

hello


In [2]:
#arg is  list as default values
def ff(L=[1,2,3]):
    for i in L:
        print(i)
    

In [5]:
/#function with variable names and values 
def printAllVariableAndValues(**args):
    for x in args:
        print("Variable names is {} and value is {}".format(x,args[x]))


In [6]:
printAllVariableAndValues(a=3,b='b',c='ccc',y=6.7)

Variable names is a and value is 3
Variable names is b and value is b
Variable names is c and value is ccc
Variable names is y and value is 6.7


# MODULES SYS


In [17]:
def sumFunction(*args):
    sum = 0
    for i in range(len(args)):
        sum +=args[i]
    print("la somme est {}".format(sum))

In [19]:
sumFunction(1,2,3,4,5,6,7,8,8,9)

la somme est 53


In [12]:
#make the modules (sys = system)
import sys
print(sys.getdefaultencoding())
print(sys.getfilesystemencoding())
print(sys.version)
print(sys.copyright)
print(sys.executable)

utf-8
utf-8
3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
Copyright (c) 2001-2021 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved.
C:\Users\dina ouahbi\anaconda3\python.exe


In [23]:
tup = sys.builtin_module_names
for i in tup[:10]:
    print('====>',i)

====> _abc
====> _ast
====> _bisect
====> _blake2
====> _codecs
====> _codecs_cn
====> _codecs_hk
====> _codecs_iso2022
====> _codecs_jp
====> _codecs_kr


In [27]:
print(sys.argv)
#the largest integer a variable can take.
print(sys.maxsize)
#path for all Python modules
print(sys.path[:5])

['C:\\Users\\dina ouahbi\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py', '-f', 'C:\\Users\\dina ouahbi\\AppData\\Roaming\\jupyter\\runtime\\kernel-44b8b8a6-8b25-448e-a689-a1bd131714e3.json']
9223372036854775807
['C:\\Users\\dina ouahbi', 'C:\\Users\\dina ouahbi\\anaconda3\\python38.zip', 'C:\\Users\\dina ouahbi\\anaconda3\\DLLs', 'C:\\Users\\dina ouahbi\\anaconda3\\lib', 'C:\\Users\\dina ouahbi\\anaconda3']
